version: "2"

build:
  os: "ubuntu-22.04"
  tools:
     python: "mambaforge-22.9"

  jobs:
    pre_build:
      - cd doc && python render.py

conda:
  environment: doc/environment.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: doc/conf.py
